name: Publishing

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

env:
  PACKAGE_PROJECT_PATH: ${{ github.workspace }}/SomeClassLibrary/SomeClassLibrary.csproj
  PACKAGE_DIRECTORY: ${{ github.workspace }}/packages
  BUILD_CONFIGURATION: Release

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build ${{ github.workspace }} --no-restore --configuration ${{ env.BUILD_CONFIGURATION }}
    - name: Package build
      run: dotnet pack ${{ env.PACKAGE_PROJECT_PATH }} --no-build --no-restore --configuration ${{ env.BUILD_CONFIGURATION }} --output ${{ env.PACKAGE_DIRECTORY }}
    - name: Add nuget source
      run: dotnet nuget add source --username ${{ github.actor }} --password ${{ secrets.NUGET_PUBLISH_TOKEN }} --store-password-in-clear-text --name GitOwnerSource https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
    - name: Package push
      id: PackagePush
      run: dotnet nuget push ${{ env.PACKAGE_DIRECTORY }}/*.nupkg --source GitOwnerSource --skip-duplicate
      continue-on-error: true
      
    - name: Create archives
      run: |
        tar -czf release-linux.tar.gz **/bin/Release/**

    - name: Upload to GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          release-linux.tar.gz
          **/*.nupkg

    - name: Remove nuget source
      run: dotnet nuget remove source GitOwnerSource
    - name: On package push failed
      if: steps.PackagePush.outcome != 'success'
      run: exit 1
