name: Publishing

on:
  push:
    tags:
      - "*"

permissions:
  contents: write
  packages: write

env:
  ARTIFACTS_DIR: ${{ github.workspace }}/bin/Release
  NUPKG_SOURCE: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
  BUILD_CONFIG: Release
  IS_MS_BUILD: true
  NUGET_JOB_INDEX: 0

jobs:
  build-and-publish:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        include:
          - os: windows-latest
            is_windows: true
          - os: ubuntu-latest
            is_windows: false
        dotnetVersion: [ 10.x, 6.x ]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0
    - name: Check if tag is on default branch
      shell: bash
      run: |
        DEFAULT_BRANCH="${{ github.event.repository.default_branch }}"
        git fetch origin $DEFAULT_BRANCH
        if git merge-base --is-ancestor $GITHUB_SHA origin/$DEFAULT_BRANCH; then
          echo "IS_DEFAULT_BRANCH=true" >> $GITHUB_ENV
        else
          echo "IS_DEFAULT_BRANCH=false" >> $GITHUB_ENV
        fi
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: ${{ matrix.dotnetVersion }}
        cache: true
        cache-dependency-path: '**/packages.lock.json'
        source-url: ${{ env.NUPKG_SOURCE }}
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Restore dependencies
      run: dotnet restore --locked-mode
    - name: Setup MSBuild
      if: env.IS_MS_BUILD == 'true' && matrix.is_windows
      uses: microsoft/setup-msbuild@v3
      with:
        msbuild-architecture: x64
    - name: MSBuild
      if: env.IS_MS_BUILD == 'true' && matrix.is_windows
      shell: bash
      run: |
        VERSION=${{ github.ref_name }}
        NO_V_VERSION=${VERSION#v}
        CLEAN_VERSION=${NO_V_VERSION%%-*}
        for solution in **/*.sln; do
          msbuild $solution \
            /t:Build \
            --property:RestorePackages=false \
            --property:Configuration=${{ env.BUILD_CONFIG }} \
            --property:Version=$CLEAN_VERSION \
            --property:InformationalVersion=$VERSION \
            --property:Platform="Any CPU"
        done
    - name: Build
      if: env.IS_MS_BUILD != 'true'
      shell: bash
      run: |
        dotnet build "${{ github.workspace }}" \
        --no-restore \
        --configuration ${{ env.BUILD_CONFIG }} \
        --property:Version="${{ github.ref_name }}" \
        --property:Platform="Any CPU"

    - name: Pack and publish
      shell: bash
      run: |
        shopt -s globstar nullglob dotglob
        for proj in **/*.csproj; do
            echo "Checking $proj"
            IS_SHIPPING_TARGET=$(dotnet msbuild "$proj" -nologo -getProperty:IsShippingTarget)
            IS_SHIPPING_TARGET=$(echo "$IS_SHIPPING_TARGET" | tr '[:upper:]' '[:lower:]')
            if [[ "$IS_SHIPPING_TARGET" == "true" ]]; then
              SHIPPING_TYPE=$(dotnet msbuild "$proj" -nologo -getProperty:ShippingType)
              IS_PACKABLE=$(dotnet msbuild "$proj" -nologo -getProperty:IsPackable)
              IS_PACKABLE=$(echo "$IS_PACKABLE" | tr '[:upper:]' '[:lower:]')
              NAME=$(basename "$proj" .csproj)
              DIR=$(dirname "$proj")
              PKG_OUT_DIR=$(dotnet msbuild "$proj" -nologo -property:Configuration=${{ env.BUILD_CONFIG }} -getProperty:PackageOutputPath)
              FULL_PKG_OUT_DIR="$DIR/$PKG_OUT_DIR"
              if [[ "$SHIPPING_TYPE" == "Archive" ]]; then
                echo "Publishing app $NAME..."
                DOTNET_MAJOR=$(echo "${{ matrix.dotnetVersion }}" | cut -d. -f1)
                APP_ARTIFACTS_DIR="${{ env.ARTIFACTS_DIR }}/$NAME-${{ github.ref_name }}.net$DOTNET_MAJOR.${{ runner.os }}"
                dotnet publish "$proj" --no-build -c ${{ env.BUILD_CONFIG }} --no-self-contained -o "$APP_ARTIFACTS_DIR"
                ZIP_NAME=$(basename "$APP_ARTIFACTS_DIR")
                (
                  cd "${{ env.ARTIFACTS_DIR }}" || exit 1
                  tar --force-local -czf "${ZIP_NAME}.tar.gz" -C "${ZIP_NAME}" .
                )
              elif [[ ${{ strategy.job-index }} == ${{ env.NUGET_JOB_INDEX }} && "$SHIPPING_TYPE" == "NuGet" && "$IS_PACKABLE" == "true" ]]; then
                echo "Packing NuGet $NAME..."
                IS_ALREADY_PACKED=$(dotnet msbuild "$proj" -nologo -getProperty:GeneratePackageOnBuild)
                IS_ALREADY_PACKED=$(echo "$IS_ALREADY_PACKED" | tr '[:upper:]' '[:lower:]')
                if [[ "$IS_ALREADY_PACKED" != "true" ]]; then
                  dotnet pack "$proj" --no-build -c ${{ env.BUILD_CONFIG }} -o ${{ env.ARTIFACTS_DIR }} --property:Version=${{ github.ref_name }}
                else
                  mkdir -p ${{ env.ARTIFACTS_DIR }}
                  cp -r -f $FULL_PKG_OUT_DIR/*.* ${{ env.ARTIFACTS_DIR }}/
                fi
              else
                echo "Skipping $NAME (non-packable library)"
              fi
            fi
          done
    - name: Upload to GitHub Release
      uses: softprops/action-gh-release@v3
      with:
        files: ${{ env.ARTIFACTS_DIR }}/*.*
        generate_release_notes: ${{ strategy.job-index == 0 }}
        append_body: false
        prerelease: ${{ env.IS_DEFAULT_BRANCH != 'true' || contains(github.ref, '-') }}
        
    - name: Package push
      if: strategy.job-index == env.NUGET_JOB_INDEX
      id: PackagePush
      run: dotnet nuget push ${{ env.ARTIFACTS_DIR }}/*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source ${{ env.NUPKG_SOURCE }} --skip-duplicate
