name: Publishing

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

env:
  NUPKG_PROJ_PATH: ${{ github.workspace }}/SomeClassLibrary/SomeClassLibrary.csproj
  NUPKG_DIR: ./nupackages
  NUPKG_SOURCE: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
  BUILD_CONFIG: Release
  CI_BUILD: true

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0
    - name: Check if tag is on default branch
      run: |
        DEFAULT_BRANCH="${{ github.event.repository.default_branch }}"
        git fetch origin $DEFAULT_BRANCH
        if git merge-base --is-ancestor $GITHUB_SHA origin/$DEFAULT_BRANCH; then
          echo "IS_DEFAULT_BRANCH=true" >> $GITHUB_ENV
        else
          echo "IS_DEFAULT_BRANCH=false" >> $GITHUB_ENV
        fi
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 9.x
        cache: true
        cache-dependency-path: '**/packages.lock.json'
    - name: Add GitOwner NuGet Source
      run: |
        dotnet nuget add source \
        --username ${{ github.actor }} \
        --password ${{ secrets.NUGET_PUBLISH_TOKEN }} \
        --store-password-in-clear-text \
        --name GitOwnerSource \
        ${{ env.NUPKG_SOURCE }}
    - name: Restore dependencies
      run: dotnet restore --locked-mode
    - name: Build
      run: |
        dotnet build ${{ github.workspace }} \
        --no-restore \
        --configuration ${{ env.BUILD_CONFIG }} \
        -p:GeneratePackageOnBuild=false \
        /p:Version=${{ github.ref_name }}
    - name: Package build
      run: |
        dotnet pack ${{ env.NUPKG_PROJ_PATH }} \
        --no-build \
        --configuration ${{ env.BUILD_CONFIG }} \
        --output ${{ env.NUPKG_DIR }} \
        /p:Version=${{ github.ref_name }}
    - name: Cleanup GitOwner NuGet Source
      if: always()
      run: dotnet nuget remove source "GitOwnerSource" || true
    - name: Create archives
      run: |
        tar -czf release-linux.tar.gz **/bin/Release/**
    - name: Upload to GitHub Release
      uses: softprops/action-gh-release@v2.6.1
      with:
        files: |
          release-linux.tar.gz
          ${{ env.NUPKG_DIR }}/*.nupkg
        generate_release_notes: true
        prerelease: ${{ env.IS_DEFAULT_BRANCH != 'true' || contains(github.ref, '-') }}
        
    - name: Package push
      id: PackagePush
      run: dotnet nuget push ${{ env.NUPKG_DIR }}/*.nupkg --api-key ${{ secrets.NUGET_PUBLISH_TOKEN }} --source ${{ env.NUPKG_SOURCE }} --skip-duplicate
